#!/usr/bin/env python

import sys
import rospy
from sorting_robot.srv import PathInPickup
from sorting_robot.msg import State


def getPathInPickup(source):
    rospy.wait_for_service('path_in_pickup')
    try:
        pathService = rospy.ServiceProxy('path_in_pickup', PathInPickup)
        response = pathService(source)
        if response is None:
            print('Received None response')
        print(type(response))
        print(response)
        print(response.path)
        return response.path
    except rospy.ServiceException, e:
        print "Service call failed: %s" % e
        sys.exit(1)


if __name__ == "__main__":
    path = getPathInPickup(State(row=17, col=7))
    path = [(pose.row, pose.col, pose.direction) for pose in path]
    print('path_in_pickup service test passed')
