#!/usr/bin/env python

from sorting_robot.utils import CoordinateSpaceManager

if __name__ == "__main__":
    csm = CoordinateSpaceManager()
    #print(csm.convertCellToPoint((9, 1)))
    #print(csm.convertCellToVector((9, 1)))
    #print(csm.convertPointToCell(csm.convertCellToPoint((9, 1))))
    path = [(9.25,34.25,1.57),(9.25,34.75,1.57),(9.25,35.25,1.57),(9.25,35.75,1.57),(9.25,36.25,1.57),(9.25,36.75,1.57),(9.25,36.75,3.14),(8.75,36.75,3.14),(8.25,36.75,3.14)];
    for i in range(0,len(path)):
	print(csm.convertPointToState(path[i]))
    #print(csm.convertPointToState((9.25,34.25,1.57)))
    print(csm.getWorldCoordinateWithDirection((46,18,90)))
