#!/usr/bin/env python

import sys
import rospy
from sorting_robot.srv import Path
from sorting_robot.msg import State


def getPath(source, destination):
    rospy.wait_for_service('path')
    try:
        pathService = rospy.ServiceProxy('path', Path)
        response = pathService(source, destination)
        return response.path
    except rospy.ServiceException, e:
        print "Service call failed: %s" % e
        sys.exit(1)


if __name__ == "__main__":
    path = getPath(State(27, 48, 180), State(60, 49, 180))
    path = [(pose.row, pose.col, pose.direction) for pose in path]
    print(path)
    print('path service test passed')
