#!/usr/bin/env python

import sys
import rospy
from sorting_robot.srv import PathToBin
from sorting_robot.msg import State


def getPathToBin(source, destination):
    rospy.wait_for_service('path_to_bin')
    try:
        pathService = rospy.ServiceProxy('path_to_bin', PathToBin)
        response = pathService(source, destination)
        return response.path
    except rospy.ServiceException, e:
        print "Service call failed: %s" % e
        sys.exit(1)


if __name__ == "__main__":
    path = getPathToBin(State(17, 7, 90), State(row=20, col=6))
    path = [(state.row, state.col, state.direction) for state in path]
    print(path)
    print('path_to_bin service test passed')
