#!/usr/bin/env python
import sys
from sorting_robot.bfsm import BFSM

if __name__ == '__main__':
    robot_name = sys.argv[1]
    map_name = sys.argv[2]
    bfsm = BFSM(robot_name=robot_name)
    bfsm.run()
