#!/usr/bin/env python

import os
import argparse
from sorting_robot.map_generation import generateGridImage


def parseArgs():
    parser = argparse.ArgumentParser(
        description="parameters for generating binary map")
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--show-turn-count', default=False,
                       action='store_true', help="shows number of turns at each cell")
    group.add_argument('--show-direction-count', default=False,
                       action='store_true', help="shows number of directions at each cell")
    parser.add_argument('--dont-save-fig', default=False,
                        action='store_true', help="whether to save the image or not")
    args = parser.parse_args()
    return not args.dont_save_fig, args.show_turn_count, args.show_direction_count


if __name__ == '__main__':
    if os.environ.get('CIRCLECI'):
        generateGridImage(saveFig=False)
    else:
        saveFig, showTurnCount, showDirectionCount = parseArgs()
        if saveFig:
            generateGridImage(saveFig=True, imageFormat='png', showDirectionCount=showDirectionCount, showTurnCount=showTurnCount)
            generateGridImage(saveFig=True, imageFormat='svg', showDirectionCount=showDirectionCount, showTurnCount=showTurnCount)
        else:
            generateGridImage(saveFig=False)
