#!/usr/bin/env python

import os
import argparse
from sorting_robot.map_generation import generateNetworkxGraph


def parseArgs():
    parser = argparse.ArgumentParser(
        description="parameters for generating binary map")
    parser.add_argument('--dont-save-fig', default=False,
                        action='store_true', help="whether to save the image or not")
    args = parser.parse_args()
    return not args.dont_save_fig

if __name__ == '__main__':
    if os.environ.get('CIRCLECI'):
        generateNetworkxGraph(saveFig=False)
    else:
        generateNetworkxGraph(saveFig=parseArgs())
