#!/usr/bin/env python

from sorting_robot.map_generation import generateBinaryMap
import argparse


def parseArgs():
    parser = argparse.ArgumentParser(
        description="parameters for generating binary map")
    parser.add_argument("-r", default=50, type=int, help="pixel to cell ratio")
    args = parser.parse_args()
    return args.r


if __name__ == '__main__':
    generateBinaryMap(parseArgs())
