#!/usr/bin/env python

from sorting_robot.stdr_initializer import generateSpawnLocations
import argparse


def parseArgs():
    parser = argparse.ArgumentParser(
        description="parameters for generating spawn locations")
    parser.add_argument("n", type=int, help="total number of robots")
    args = parser.parse_args()
    return args.n


if __name__ == '__main__':
    generateSpawnLocations(parseArgs())
