#!/usr/bin/env python

from sorting_robot.system_initialization import executeOneByOne, executeAllAtOnce
import argparse


def parseArgs():
    parser = argparse.ArgumentParser(
        description="parameters for spawning_robots_from_script")
    parser.add_argument('--all-at-once', default=False,
                        action='store_true', help="whether to spawn the robots one by one with delay between the calls")
    args = parser.parse_args()
    return args.all_at_once


if __name__ == '__main__':
    all_at_once = parseArgs()
    if not all_at_once:
        executeOneByOne()
    else:
        executeAllAtOnce()
